"""Guard: X19 — the fan coil unit onboarded config-only. Run 1 fired two
falsifiers (deployed FP 28/96; six scenarios by the model channel alone), both
traced to the scripts' silent-while-scheduled rule counting setback as
operation and the scorecard's model gate using a smaller baseline than the
deployed count. Amendment 1 (scripts only) repaired both; the four earlier
systems regenerated byte-identically; run 2: 41/47 at 4/96, no falsifier."""
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "outputs" / "x19_onboarding.json"
RUN1 = ROOT / "outputs" / "x19_onboarding_run1.json"


def test_x19_run2_pinned():
    if not ART.exists():
        pytest.skip("artifact absent")
    a = json.loads(ART.read_text())
    p = a["predictions"]
    assert a["falsifiers_fired"] == []
    assert p["P1_config_only"] and p["P4_fp_le_10_of_96"] and p["P5_ge_60pct"] and p["P7_null_generalises"] and p["P8_holds"]
    assert p["P2_gates"] is False and p["P2_axes"]["G1_no_duplicates"] is False and p["P2_axes"]["G5_ttl_covers_columns_by_name"] is False
    assert all(p["P2_axes"][k] for k in ("G2_monotonic", "G3_calendar_identical", "G4_no_rotation", "G6_healthy_inside_cluster"))
    assert p["P3_healthy_silence_iterations"] == 2
    assert (p["P5_detected"], p["P5_n_scored"]) == (41, 47) and p["P4_holdout_fp_days"] == 4
    assert (p["P6_fouling_detected"], p["P6_fouling_scored"]) == (6, 11) and p["P6_le_6"]
    assert (p["P8_airflow_detected"], p["P8_control_detected"]) == (5, 3)
    assert p["P7_conformance_only_scenarios"] == []
    assert a["effort"]["src_diff_since_prereg"] == "none"
    assert (a["effort"]["sensor_mappings"], a["effort"]["state_rules"], a["effort"]["signature_rules"]) == (30, 7, 16)   # 30 incl. Datetime
    assert a["gates"]["duplicates"] == [["FCU_Fouling_Cooling_Airside_Minor.csv", "FCU_Fouling_Heating_Airside_Minor.csv"]]
    assert a["gates"]["excluded_scenarios"] == ["FCU_Fouling_Heating_Airside_Minor"]
    s = a["scorecard"]
    assert s["by_family"] == {"oa_damper_leak": [2, 3], "oa_damper_stuck": [5, 5], "valve_leak": [6, 6], "valve_stuck": [10, 10],
                              "sensor_bias": [4, 4], "coil_fouling": [6, 11], "airflow_restriction": [5, 5], "control_fault": [3, 3]}
    assert s["channels"]["model"] == 7 and s["channels"]["device"] == 0   # model credit only beside other channels (P7)
    assert s["per_channel_fp"] == {"rules": 0, "resid": 3, "model": 1, "device": 0, "absence": 0, "freq": 0, "rate": 17, "osc": 0}
    assert sorted(s["misses"]) == sorted(["FCU_OADMPRLeak_20", "FCU_Fouling_Cooling_Waterside_Minor", "FCU_Fouling_Cooling_Waterside_Moderate",
                                          "FCU_Fouling_Cooling_Waterside_Severe", "FCU_Fouling_Heating_Waterside_Minor", "FCU_Fouling_Heating_Waterside_Moderate"])


def test_x19_run1_kept_with_fired_falsifiers():
    if not RUN1.exists():
        pytest.skip("artifact absent")
    r = json.loads(RUN1.read_text())
    assert [f.split(":")[0] for f in r["falsifiers_fired"]] == ["F-X19.b", "F-X19.d"]
    assert r["predictions"]["P4_holdout_fp_days"] == 28 and r["predictions"]["P5_detected"] == 47
    assert len(r["predictions"]["P7_conformance_only_scenarios"]) == 6
    u1 = json.loads((ROOT / "outputs" / "union_fpr_fcu_run1.json").read_text())
    dates = u1["channels"]["model"]["holdout_fp_dates"]
    import datetime
    assert len(dates) == 25 and all(datetime.date.fromisoformat(d).weekday() >= 5 for d in dates)
